stock_targets = [
    ("1326.TW", "台化"),
    ("2904.TW", "匯僑"),
    ("2414.TW", "精技"),
    ("2330.TW", "台積電"),
    ("2317.TW", "鴻海"),
    ("2324.TW", "仁寶"),
    ("2347.TW", "聯強"),
    ("2376.TW", "技嘉"),
    ("2414.TW", "精技"),
    ("2489.TW", "瑞軒(零_出)"),
    ("2887.TW", "台新金"),
    ("2891.TW", "中信金"),
    ("2904.TW", "匯僑"),
    ("3211.TWO", "順達"),
    ("6101.TWO", "寬魚國際_出"),
    ("6189.TW", "豐藝"),
    ("6216.TW", "居易"),
    ("0050.TW", "元大台灣50_低買"),
    ("0056.TW", "元大高股息_低買"),
    ("00919.TW", "群益台灣精選高息_低買"),
    ("00875.TW", "國泰網路資安"),
    ("009802.TW","富邦旗艦50"),
    ("009816.TW","凱基台灣TOP50"),
    ("00942B.TWO","台新美A公司債"),
    ("2308.TW", "台達電_無"),
    ("1295.TWO", "生合生技_益生菌.增肌減脂"),
    ("AAL", "American Airlines"),
    ("AAPL", "Apple"),
    ("AMZN", "Amazon"),
    ("CELH", "Celsius 運動飲料80"),
    ("META", "FaceBook"),
    ("NFLX", "Netflix"),
    ("NVDA", "NVIDIA"),
    ("O", "Realty Income"),
    ("QQQ", "Invesco QQQ"),
    ("SPY", "SPDR S&P 500"),
    ("T", "AT&T"),
    ("TSLA", "Tesla"),
    ("ZIM", "以星航運"),
    ("VTI", "Vanguard Total Stock Mkt"),
    ("MSFT", "Microsoft"),
    ("COST", "Costco"),
    ("WRD", "中國廣東.文遠知行.自動駕駛技術開發"),
    ("QS", "QuantumScape.開發新型固態鋰金屬電池")
]
receiver_email = "mingsyun@hotmail.com"
